# SECTION-A   Output Prediction 

Q1.  Array operations and vectorization

import numpy as np

import pandas as pd

arr = np.array([10, 20, 30])

s = pd.Series([10, 20, 30])

print(arr * 2)

print(s * 2)

Predict the output of both statements.

Ans:

[20 40 60]

0    20

1    40

2    60

dtype: int64

Identify one similarity and one difference between the two data structures.

Ans:

Similarity: Both support vectorized operations and multiply every element by 2.
Difference: NumPy array does not have an index, while Pandas Series has an index.


In [1]:
import numpy as np
import pandas as pd

arr = np.array([10, 20, 30])
s = pd.Series([10, 20, 30])

print(arr * 2)
print(s * 2)

[20 40 60]
0    20
1    40
2    60
dtype: int64


Q2. Boolean Filtering

Question: Predict the rows displayed.

Ans:

  Student  Marks

1       B     80

2       C     65

3       D     90

 How many rows and columns will the resulting DataFrame contain?
Ans: 

3 rows and 2 columns.
Explanation:

 df['Marks'] >= 65 selects students whose marks are 65 or above.

In [4]:
import pandas as pd

df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Marks': [45, 80, 65, 90]
})

result = df[df['Marks'] >= 65]

print(result[['Student', 'Marks']])

  Student  Marks
1       B     80
2       C     65
3       D     90


Q3. Descriptive Statistics

Question: Predict all three outputs.

Ans:

30.0

50

30.0

Explain how the median differs from the mean.

Ans: 

Mean is the average of all values, while median is the middle value after arranging the values in order. Here, both are 30.

In [5]:
import pandas as pd

df = pd.DataFrame({
    'Marks': [10, 20, 30, 40, 50]
})

print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].median())


30.0
50
30.0


Q4. Group-wise Analysis

Question: Predict the output.

Ans:

Department

HR    40000.0

IT    50000.0

Name: Salary, dtype: float64

Explain how groupby() calculates the department-wise average.

Ans: 

groupby('Department') separates the data into HR and IT groups, and mean() calculates the average salary of each group.

In [6]:
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [40000, 30000, 60000, 50000]
})

print(df.groupby('Department')['Salary'].mean())


Department
HR    40000.0
IT    50000.0
Name: Salary, dtype: float64


Q5. Pandas Correlation – Positive

Question: Predict the correlation coefficient.

Ans:

1.0

Interpret the direction and strength of the relationship.

Ans:

 +1.0 indicates a perfect positive correlation. As Hours increase, Marks also increase.

In [8]:
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))


1.0


Q6. Pandas Correlation – Negative

Question: Predict the correlation coefficient.

Ans:

-1.0

Explain what the sign of the coefficient indicates about the relationship.

Ans: 

The negative sign indicates an inverse relationship. As Price increases, Demand decreases. -1.0 represents a perfect negative correlation.

In [9]:
import pandas as pd

df = pd.DataFrame({
    'Price': [10, 20, 30, 40],
    'Demand': [100, 80, 60, 40]
})

print(df['Price'].corr(df['Demand']))


-1.0


# Section B – Code Correction

Q1. JSON and CSV

A CSV file contains a header row, but the following code incorrectly reads the first student's record as column names. Correct the code.

import pandas as pd

df = pd.read_csv("students.csv", header=None)

print(df)    

Issue:
 header=None tells Pandas that the CSV file has no header.

Corrected Code:

import pandas as pd

df = pd.read_csv("students.csv", header=0)

print(df)

Explanation:

 header=0 tells Pandas that the first row contains the column names, so the first student's record is not used as a header.

In [1]:
import pandas as pd
print("Pandas imported successfully")
print(pd.__version__)

Pandas imported successfully
3.0.6


In [3]:
import pandas as pd

df = pd.read_csv("student.csv", header=0)
print(df)

  Student  Marks
0       A     45
1       B     80
2       C     65
3       D     90


Q2. Data Analysis

The objective is to display the five highest salaries from a DataFrame. Correct the code.

Issue: sort_values('Salary') sorts salaries in ascending order, so head(5) gives the five lowest salaries.

Corrected Code:

import pandas as pd

df = pd.DataFrame({

    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],

    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

print(df.sort_values('Salary', ascending=False).head(5))

Explanation: 

Ascending=False sorts salaries from highest to lowest, and head(5) selects the first five.


In [4]:
import pandas as pd

df = pd.DataFrame({

    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],

    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

print(df.sort_values('Salary', ascending=False).head(5))

  Employee  Salary
5        F   70000
3        D   60000
1        B   50000
4        E   45000
0        A   30000


Q3. Cleaning Data

A student wants to replace missing marks with the column's mean but writes code that does not update the DataFrame. Correct the code.

Issue:

 fillna() returns the updated Series, but the result was not assigned back to the DataFrame.

Corrected Code:

import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

print(df)

Explanation: 

The mean of 70 and 90 is 80, and assigning the result back to df['Marks'] replaces the missing value.

In [5]:
import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

print(df)

   Marks
0   70.0
1   80.0
2   90.0


Q4. Correlation

The objective is to calculate the correlation between Hours and Marks. Correct the code.

Issue: 

df.corr() does not take column names as positional arguments like that.

Corrected Code:

import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))

Explanation: 

corr() calculates the Pearson correlation between the Hours and Marks columns; 1.0 means a perfect positive correlation.

In [6]:
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))

1.0


## Section C – Edge Cases

Q1. Two NumPy arrays have shapes (3, 1) and (1, 3). Predict the shape of their element-wise sum and explain how broadcasting works. Why might the result differ from adding two one-dimensional arrays?

import numpy as np

a = np.array([[10], [20], [30]])

b = np.array([[1, 2, 3]])

result = a + b

print(result)

print(result.shape)

1: Predict the output of the given code.


In [7]:
import numpy as np

a = np.array([[10], [20], [30]])
b = np.array([[1, 2, 3]])

result = a + b

print(result)
print(result.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)


2: Identify the shapes of arrays a and b before addition.

Ans:

Shape of a: (3, 1)

Shape of b: (1, 3)

3:  Explain how NumPy broadcasting enables the addition of these arrays.

Ans:

 Broadcasting automatically expands the arrays to compatible shapes without explicitly copying their values. Array a is expanded across columns, and array b is expanded across rows, producing a (3, 3) result.

 What would happen if b were replaced with np.array([1, 2])? Explain the reason.

Ans:

 A ValueError occurs because the shapes (3, 1) and (2,) are not compatible for broadcasting. Their dimensions do not match and neither dimension is 1.

 Explanation: 
 
 Reshaping b to (1, 3) makes the arrays compatible for broadcasting.

In [8]:
b = np.array([1, 2, 3]).reshape(1, 3)
result = a + b

print(result)
print(result.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)


Q2. A CSV file contains commas inside quoted text fields, missing values, and dates in different formats. Explain how incorrect parsing can affect the resulting DataFrame and identify suitable read options or preprocessing steps.

Given dataset: students.csv
ID,Name,Date,Marks
101,"Asha, R",2026-09-01,80
102,Ravi,01/09/2026,
103,Neha,2026-09-03,NA

Given code:
import pandas as pd

df = pd.read_csv("students.csv")

print(df)
print(df.dtypes)

1: Predict how the quoted comma in "Asha, R" will be handled when the CSV file is read.

Ans:

 Pandas correctly treats "Asha, R" as a single field because the comma is inside double quotes. It will not split the name into two columns.

2: Identify the potential issues with the Date and Marks columns.

Ans:

Date: Dates are in different formats, such as 2026-09-01 and 01/09/2026, which may cause inconsistent parsing.

Marks: Blank values and "NA" may represent missing data. They should be checked and converted appropriately.

3: Rewrite the code to handle missing marks and convert the date column into a suitable date-time format.


In [11]:
import pandas as pd
from io import StringIO

data = """ID,Name,Date,Marks
101,"Asha, R",2026-09-01,80
102,Ravi,01/09/2026,
103,Neha,2026-09-03,NA"""

df = pd.read_csv(StringIO(data), na_values=["", "NA"])

df.columns = df.columns.str.strip()

df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

df["Date"] = pd.to_datetime(
    df["Date"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

print(df)
print(df.dtypes)

    ID     Name       Date  Marks
0  101  Asha, R 2026-01-09   80.0
1  102     Ravi 2026-09-01    NaN
2  103     Neha 2026-03-09    NaN
ID                int64
Name                str
Date     datetime64[us]
Marks           float64
dtype: object


4: Explain why the value "NA" should be investigated before deciding whether it represents a missing value.

Ans:

 "NA" may represent a missing mark, but it could also be a valid code or text value. It should be checked before replacing it to avoid losing meaningful information.

Explanation:

 na_values identifies specified missing-value markers, to_numeric() converts marks into numeric values, and to_datetime() converts dates into a consistent date-time format. errors="coerce" converts invalid values into NaN or NaT for further investigation

Q3. A salary column contains the values 25000, 30000, 35000, and 10000000. Explain how the extreme value affects the mean compared with the median. Identify which statistic may better represent a typical employee's salary and justify your choice.

Given code:

import pandas as pd

df = pd.DataFrame({

    "Employee": ["A", "B", "C", "D"],

    "Salary": [25000, 30000, 35000, 10000000]
})

print("Mean:", df["Salary"].mean())

print("Median:", df["Salary"].median())

1: Predict the mean and median salary.

Ans:

Given salaries:

25000, 30000, 35000, 10000000

Mean:

25000+30000+35000+10000000 / 4

Mean = 2,522,500.0

Median:

30000+35000/2

Median = 32,500.0

2: Identify the effect of the extreme salary on the mean.

Ans:

 The extreme salary of ₹1,00,00,000 increases the mean significantly, making it much higher than the other employees' salaries. 

3: Which statistic may better represent a typical employee's salary in this dataset? Justify your answer.

Ans:

 The median (₹32,500) may better represent a typical employee's salary because it is not affected much by the extreme salary. The mean is pulled upward by the outlier, while the median represents the middle value of the dataset.

4: Write code to identify the employee record with the highest salary and explain why the record should be investigated before removing it.

Explanation: idxmax() identifies the index of the highest salary, and loc[] retrieves the complete employee record.

Code:

In [12]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Salary": [25000, 30000, 35000, 10000000]
})

highest_salary = df.loc[df["Salary"].idxmax()]

print(highest_salary)

Employee           D
Salary      10000000
Name: 3, dtype: object


Q1:Student Assessment Dataset Cleaning Using Pandas

Question: Using Pandas, perform the following cleaning operations in sequence:

-> Load the CSV file and inspect the dataset using head(), info(), and isnull().sum().

-> Standardize department names such as IT, it, and I.T. Apply the same approach to Finance.

-> Identify and remove exact duplicate records.

-> Convert Marks into numeric format, handling "88 marks", "Absent", "NA", and blank entries.

-> Investigate missing marks and distinguish absent students from students whose marks have not been entered. State one risk of deleting missing values without investigating why they are missing.

-> Identify marks outside the valid range of 0–100 and decide how they should be handled.

-> Display the cleaned DataFrame and report the number of records removed, missing marks remaining, and invalid marks identified.

In [15]:
import pandas as pd
from io import StringIO

data = """Student_ID,Student_Name,Department,Assessment,Marks
S101,Asha,IT,Python,85
S102,Ravi,it,Python,78
S103,Neha,I.T.,Python,92
S104,Karan,HR,Python,
S105,Meera,HR,Python,Absent
S106,Arjun,Finance,Python,0
S107,Priya,finance,Python,67
S108,Rahul,IT,Python,75
S102,Ravi,it,Python,78
S109,Sneha,I.T.,Python,NA
S110,Varun,HR,Python,88 marks
S111,Diya,Finance,Python,91
S112,Aman,IT,Python,
S113,Nisha,HR,Python,64
S114,Kabir,Finance,Python,105
"""

df = pd.read_csv(StringIO(data))

df["Department"] = df["Department"].str.strip().str.upper()
df["Department"] = df["Department"].replace("I.T.", "IT")

df = df.drop_duplicates()

df["Marks"] = (
    df["Marks"].astype(str)
    .str.replace("marks", "", case=False)
    .str.strip()
    .replace(["", "NA", "ABSENT", "NAN"], pd.NA)
)

df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

df.loc[df["Marks"] > 100, "Marks"] = pd.NA

df["Marks"] = df.groupby("Department")["Marks"].transform(
    lambda x: x.fillna(x.median())
)

print("Cleaned Dataset:")
print(df)

print("\nData Types:")
print(df.dtypes)

Cleaned Dataset:
   Student_ID Student_Name Department Assessment  Marks
0        S101         Asha         IT     Python   85.0
1        S102         Ravi         IT     Python   78.0
2        S103         Neha         IT     Python   92.0
3        S104        Karan         HR     Python   76.0
4        S105        Meera         HR     Python   76.0
5        S106        Arjun    FINANCE     Python    0.0
6        S107        Priya    FINANCE     Python   67.0
7        S108        Rahul         IT     Python   75.0
9        S109        Sneha         IT     Python   81.5
10       S110        Varun         HR     Python   88.0
11       S111         Diya    FINANCE     Python   91.0
12       S112         Aman         IT     Python   81.5
13       S113        Nisha         HR     Python   64.0
14       S114        Kabir    FINANCE     Python   67.0

Data Types:
Student_ID          str
Student_Name        str
Department          str
Assessment          str
Marks           float64
dtype: obj

Risk of deleting missing values:

Deleting missing values without investigation may cause loss of important student information and lead to biased results.

Justification:

Pandas is used because it provides simple methods for data cleaning, duplicate removal, missing value handling, and numeric conversion. CSV is suitable for storing student assessment data in tabular form.

Explanation:

-> head(), info(), and isnull().sum() inspect the dataset.

-> replace() standardizes department names.

-> drop_duplicates() removes repeated records.

-> to_numeric() converts marks into numeric values.

-> Absent, NA, and blank entries are treated as missing, but absence is kept distinguishable as a reason for missingness during investigation.

->Marks outside 0–100 are identified and treated as invalid.